on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: R-CMD-check

jobs:
  R-API:
    name: R imlementation
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2 # checkout repo into $GITHUB_WORKSPACE

      - uses: r-lib/actions/setup-r@v1
        with:
             r-version: release
      - name: Install local registry
        run: /bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
      - name: Install system requirements (macOS-latest)
        if: matrix.config.os == 'macos-latest'
        run : |
               rm '/usr/local/bin/gfortran'
               brew install hdf5
               brew install gdal
      - name: Install R API implementation
        run: |
             install.packages("remotes")
             remotes::install_github("FAIRDataPipeline/rFDP")
        shell: Rscript {0}
      - name: Run examples
        run: Rscript scripts/examples.R
      - name: Stop registry
        run: /Users/runner/.fair/registry/scripts/stop_fair_registry
      - name: Archive sqlite3 db
        uses: actions/upload-artifact@v2
        with:
          name: R-sqlite3-db
          path: /Users/runner/.fair/registry/db.sqlite3
      - name: Archive working configs
        uses: actions/upload-artifact@v2
        with:
          name: working-configs
          path: ${{ github.workspace }}/test/datastore/coderun/

  Julia-API:
    name: Julia implementation
    needs: R-API
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2 # checkout repo into $GITHUB_WORKSPACE
      - uses: r-lib/actions/setup-r@v1
        with:
             r-version: release

      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.6.2
      - name: Install local registry
        run: /bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
      - name: Install Julia API Implementation
        run: julia --project=test/ -e 'using Pkg; Pkg.add("SQLite"); Pkg.add("DataFrames"); Pkg.develop(url="https://github.com/FAIRDataPipeline/DataRegistryUtils.jl"); Pkg.instantiate()'
      - name: Start registry
        run: /Users/runner/.fair/registry/scripts/start_fair_registry
      - name: Download working configs
        uses: actions/download-artifact@v2
        with:
          name: working-configs
      - name: Run examples
        run: julia scripts/examples.jl
      - name: Stop registry
        run: /Users/runner/.fair/registry/scripts/stop_fair_registry
      - name: Archive sqlite3 db
        uses: actions/upload-artifact@v2
        with:
          name: julia-sqlite3-db
          path: /Users/runner/.fair/registry/db.sqlite3
      - name: Download R-sqlite3-db
        uses: actions/download-artifact@v2
        with:
          name: R-sqlite3-db
      - name: Compare databases
        run: Rscript test_SQLite_db.R









